### ISSUE TITLE
How to enable upload image as base64image?

### ISSUE THREAD

**Issue by codetinker** [HstarComponents/ngx-ckeditor#1]
Hello.

I don't even see a upload image button. 
Read on ckeditor web that a plugins need to be downloaded to use function. 
But how to enable this on angular 4?

**Comment by hstarorg** [comment]
The `ngx-ckeditor` is only a ckeditor wrapper. You can add the plugin into ckeditor and then can use it in `ng-ckeditor`.

Later, I'll update the demo to show this function.

**Comment by hstarorg** [comment]
@codetinker You can extension the ck-editor, like demo: 
https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/app/app.component.ts#L26-L60
