### ISSUE TITLE
Word count issue in full and standard version of ckeditor 

### ISSUE THREAD

**Issue by deep3092** [HstarComponents/ngx-ckeditor#14]
I am using the  full version of the editor . The package works fine, but there is issue with the word count . 
I am not able to get the word count in the editor section . 

The same functionality works fine in basic version , but not in standard and full version. 
The required packages/plugins are added . 

Is there any issue in using the word count in full version/standard version? 

We are using angular 5 , browser - IE

**Comment by hstarorg** [comment]
This is not the `ngx-ckeditor` issue. Mabey you can use my demo to try it. Demo: https://hstarcomponents.github.io/ngx-ckeditor/#/form
Demo Source Code:https://github.com/HstarComponents/ngx-ckeditor/tree/master/examples/pages/reactive-form-demo

**Comment by hstarorg** [comment]
Demo provided.
