### ISSUE TITLE
ngx-ckeditor Basic version copy/paste issue

### ISSUE THREAD

**Issue by deep3092** [HstarComponents/ngx-ckeditor#16]
I'm using Basic version of ckeditor . while pasting text inside ckeditor not fire any events. But in full version of ckeditor this issue is not happening.
framework:  Angular5 . please help ..

**Comment by hstarorg** [comment]
Would you provide a simple demo?

**Comment by deep3092** [comment]
sorry i can't provide . working in virtual machine .  in my plugin folder clipboard/dialog/paste.js file placed and word count plugin also. is there other plugin required for paste event ?

**Comment by hstarorg** [comment]
The `ngx-ckeditor` is a light wrapper for `ckeditor`, maybe you should find the answer with `ckeditor`.

**Comment by hstarorg** [comment]
The question not reproduce, close the issue.
