### ISSUE TITLE
How to configure globally in Angular 5?

### ISSUE THREAD

**Issue by aeslinger0** [HstarComponents/ngx-ckeditor#17]
I see there's a `config` attribute that allows you to configure a single instance of the editor. Is there a way to configure global defaults within Angular 5?

**Comment by hstarorg** [comment]
Sorry, no way. I think you can configure a global config by yourself, and set it to every editor.

**Comment by AhHa45** [comment]
how should a config object look like? The link in the readme just points to ckeditor docs website...

**Comment by hstarorg** [comment]
@AhHa45 Actually, the configation object is also like ckeditor docs. See the [demo config object](https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/pages/reactive-form-demo/reactive-form-demo.component.ts)
