### ISSUE TITLE
Angular Material Tabs

### ISSUE THREAD

**Issue by Moccup** [HstarComponents/ngx-ckeditor#19]
There is an issue when using with Angular Material, when switching tabs via angular material tabs the ckeditor component freezes. Is there a simple solution for this?

**Comment by hstarorg** [comment]
That will help us resolve the question quickly if you can provide an useful demo.

**Comment by hstarorg** [comment]
Repeat with #38.

**Comment by hstarorg** [comment]
Please try with ngx-ckeditor@beta, thanks. Demo in https://hstarcomponents.github.io/ngx-ckeditor/#/material-tab

**Comment by hstarorg** [comment]
Published with tag `latest`.
