### ISSUE TITLE
CKEditorModule is not an NgModule : web pack

### ISSUE THREAD

**Issue by jitugeo-ma** [HstarComponents/ngx-ckeditor#20]
I'm getting a compilation error "CKEditorModule is not an NgModule".
 I'm using the following delopment environment 
1. angular 4.x 
2. ngx-ckeditor@0.2.0
3. angular cli: 1.4.10

Findings: the file ck-editor.module.d.ts (ngx-ckeditor/lib/src/ck-editor.module.d.ts) does not have @NgModule({}) annotation. After ngx-CKEditor npm installed, if i add the following code it works.

import { NgModule } from "@angular/core";
@NgModule({})
export declare class CKEditorModule {
}

@hstarorg 
Can you guys pls add this code if I'm not missing anything. I don't have access to create a pull request against the master branch. 

Thank you,
Jitender

**Comment by hstarorg** [comment]
Thanks for your code. The `ngx-ckeditor@0.2.1` published.

**Comment by jitugeo-ma** [comment]
thank you for the change. after updating with 0.2.1
I started getting en error "The editor instance "editor-70847303" is already attached to the provided element"
the code change 
import { NgModule } from '@angular/core';
@NgModule({})
in file CKEditorModule with version 2.0 was working fine in my local.
can you pleas look into this @hstarorg 
thank you,
Jitender

**Comment by hstarorg** [comment]
I'm sorry, the latest 0.2.x version is `0.2.3`

**Comment by jitugeo-ma** [comment]
thanks @hstarorg . it works.

**Comment by hstarorg** [comment]
Resolved issue, close.
