### ISSUE TITLE
How to hide the footer section of the editor??

### ISSUE THREAD

**Issue by sarath3940** [HstarComponents/ngx-ckeditor#23]
Is there any way for hidding the footer section of the editor window??
![dgh](https://user-images.githubusercontent.com/37688535/41530943-6335c878-730f-11e8-8b7f-67d148b2f2c9.png)

**Comment by hstarorg** [comment]
Sorry, I don't know. Maybe you can find the answer from https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html

**Comment by hstarorg** [comment]
@sarath3940 See https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbar
