### ISSUE TITLE
How to hide the Bold, Italic and Underline menu from the toolbar

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [HstarComponents/ngx-ckeditor#24]
Hi,
Can u please tell me How to hide the Bold, Italic and Underline menu from the toolbar menus.

Thanks in advance

**Comment by hstarorg** [comment]
Maybe you can find the answer from https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html

**Comment by PrabakarKaruppasamy** [comment]
@hstarorg  Thanks a lot. I got it.

**Comment by hstarorg** [comment]
@PrabakarKaruppasamy ok, the ck-editor has more options. In fact, I also find my editor config from official  document.

**Comment by PrabakarKaruppasamy** [comment]
Great I'm closing this issue. Thanks
