### ISSUE TITLE
How we can make some part of the text is not editable in CKEditor?

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [HstarComponents/ngx-ckeditor#25]
This is the text I want to show in the CKEditor.

<p>Hello {{{name}}}, As per your subscription this is your listing. <span>The price of your listing has been reduced, have a look</span></p>

Can I make the text between the span tag is not editable?

**Comment by hstarorg** [comment]
In my understanding, ckeditor can't make part elements editable.

**Comment by hstarorg** [comment]
No more messages, so close the issue now.
