### ISSUE TITLE
Error when "inline"=true

### ISSUE THREAD

**Issue by RandCh** [HstarComponents/ngx-ckeditor#28]
I am using Angular 5.2 + Ionic 3.20
It prompt an error when i set inline to true 
 "Cannot read property 'clearCustomData' of undefined"

**Comment by hstarorg** [comment]
Would you provide a simple demo? `clearCustomData` is not in my code.

**Comment by RandCh** [comment]
It should be come from ckeditor.js. 
TypeError: Cannot read property 'clearCustomData' of undefined
    at a.<anonymous> (http://cdn.ckeditor.com/4.7.1/full/ckeditor.js:341:414)
    at a.n (http://cdn.ckeditor.com/4.7.1/full/ckeditor.js:10:224)
    at a.<anonymous> (http://cdn.ckeditor.com/4.7.1/full/ckeditor.js:12:47)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (http://cdn.ckeditor.com/4.7.1/full/ckeditor.js:13:242)
    at a.destroy (http://cdn.ckeditor.com/4.7.1/full/ckeditor.js:270:148)

without the inline property, everything is work fine. 

I might provide a sample later. Thanks.

**Comment by hstarorg** [comment]
@RandCh Okay,tks.

**Comment by Braste** [comment]
Same problem here with ckeditor.js 4.7.1 and 4.10.0, Angular 6.0.9 with Angular CLI 6.1.5. It worked without issues before doing an update of the following packages:

+ karma-jasmine@1.1.2
+ karma-coverage-istanbul-reporter@1.4.3
+ codelyzer@4.4.4
+ @types/jasmine@2.8.8
+ @ng-bootstrap/ng-bootstrap@1.1.2
+ core-js@2.5.7
+ rxjs-compat@6.3.1
+ @angular/cli@6.1.5
+ karma@2.0.5
+ protractor@5.4.0
+ rxjs@6.3.1
+ @types/node@6.0.117
+ angular-calendar@0.23.7
+ ngx-date-fns@1.13.4

**Comment by hstarorg** [comment]
@Braste Thanks. Would you commit an pr?

**Comment by Braste** [comment]
pr?

**Comment by Braste** [comment]
I tested some more and i found the issue. With 0.3.2 you added this:

  ngAfterViewInit() {
    this.destroyCKEditor();
    this.initCKEditor(CKEditorComponent.getRandomIdentifier(this.id));
  }

Here is the problem. When ndAfterViewInit gets called, the "loaded" event of the CKEditor-Object is not fired. When the CKEditor-Object is an inline editor, the "destroy" event of it calls container.clearCustomData(), but the container-property gets filled in the "loaded" event, so it is empty when the "destroy" event is called.

I "fixed" it by replacing

`this.ckIns = this.inline`
`            ? CKEDITOR.inline(this.ck.nativeElement, opt)`
`            : CKEDITOR.replace(this.ck.nativeElement, opt);`

in ck-editor.component.ts with
 
` if (this.inline) {`
`            this.ckIns = CKEDITOR.inline(this.ck.nativeElement, opt);`
`            let a = CKEDITOR.dom.element.get(this.ck.nativeElement);`
`            let c = a.is("textarea") ? a : null;`
`            this.ckIns.container = CKEDITOR.dom.element.createFromHtml('\x3cdiv contenteditable\x3d"' + !!opt.readOnly + '" class\x3d"cke_textarea_inline"\x3e' + c.getValue() + "\x3c/div\x3e", CKEDITOR.document);`
`        }`
`        else {`
`            this.ckIns = CKEDITOR.replace(this.ck.nativeElement, opt);`
`        }`

simulating some of the code within ckeditor.js

With this the "destroy" event of ckeditor can fire successfully.

**Comment by RandCh** [comment]
Woo, Braste, you are my hero. I also located the problem in ck-editor.component.ts, but i haven't imaged using 'ckeditor.js' coding to replace that code to solve the issues. 
Thanks a lot!

**Comment by hstarorg** [comment]
@Braste Thanks a lot.
