### ISSUE TITLE
Data is not appear in ckeditor using router link, But when I reload the page data is appear. How can I resolve this issue.

### ISSUE THREAD

**Issue by rahulsetia25** [HstarComponents/ngx-ckeditor#3]
Data is not appear in ckeditor using router link, But when I reload the page data is appear. How can I resolve this issue.

<ck-editor name="description"  formControlName='description' [(ngModel)]="this.description" value="this.description"skin="moono-lisa" lang="en" [fullPage]="true"></ck-editor>

**Comment by hstarorg** [comment]
Thanks for your feedback, would you provide a useful demo?

**Comment by gredenham** [comment]
I have the same problem, when I go to the page with the editor, I get data from the server, based on the id from the URL, but the values ​​are not added to the editor. If the page is reloaded, then everything is fine

**Comment by hstarorg** [comment]
@gredenham Thanks, would you provide a useful demo?

**Comment by Braste** [comment]
Two comments.
First: You should use "description", not "this.description"
Second: Did you try it with an *ngIf="description"? It is quite normal, that data aren't present when the dom get's loaded, if the variable isn't already filled. *ngIf="description" would check this and automatically (re)load the element, if description get's filled.

**Comment by hstarorg** [comment]
Please see [demo](https://hstarcomponents.github.io/ngx-ckeditor/)
