### ISSUE TITLE
Underline button missing

### ISSUE THREAD

**Issue by mitul69** [HstarComponents/ngx-ckeditor#31]
Hello, 

I am using CKEditor in angular 5 project but underline button is missing,

Can you please give me steps how can i change it's from Standard to Full, or how can i add underline button

**Comment by hstarorg** [comment]
Only add the full ckeditor in your project.The `ngx-ckeditor` is only a simple wrapper with `ckeditor`.

**Comment by mitul69** [comment]
How can i add full ckeditor in Angular 5 project ?

**Comment by hstarorg** [comment]
With `script` tag.
