### ISSUE TITLE
ngOnChanges method in ck-editor.component cause editor-incorrect-destroy

### ISSUE THREAD

**Issue by ymchun** [HstarComponents/ngx-ckeditor#33]
I have single editor on a page and the editor config is passed via input variable to ckeditor component. This may trigger `initCKEditor` method multiple times causing `editor-incorrect-destroy` error.

I have tested commenting the `ngOnChanges`, no error was thrown.

**Comment by hstarorg** [comment]
thanks for your feedback,I'll process that.

**Comment by hstarorg** [comment]
I add a demo for you, https://hstarcomponents.github.io/ngx-ckeditor/#/dynamic-config

**Comment by ymchun** [comment]
@hstarorg what is this demo for? I can see the same warning is thrown on your demo.

**Comment by hstarorg** [comment]
I can't see some warnings/errors in chrome console. Would you take a screenshot and provider reproduce steps. Very thanks.

**Comment by ymchun** [comment]
just go into the page and got the error

![image](https://user-images.githubusercontent.com/282311/46961597-adf52080-d0d3-11e8-8dbc-da76bd8173fb.png)

**Comment by hstarorg** [comment]
Sorry, I can't see the error in my browser(64.0.3282.140 64-bit).
I'll upgrade to chrome 69 and try again. Thanks.

**Comment by ymchun** [comment]
Just to clarify that what I mean "error" is that yellow warning in the console, this is error thrown by ckeditor. Thank you for your help :)

**Comment by hstarorg** [comment]
@ymchun I think I'm understand now. Sure, ckeditor will throw the error when editor is being destroyed before it is fully initialized.
I'll try to fix it.Thanks for your feedback.

**Comment by joehansen** [comment]
@hstarorg First, thanks for your work :-)

Are there any updates for this issue yet? 

We have several Editors on page, so there are many warnings in the logs

**Comment by hstarorg** [comment]
I'll refactoring this lib with `@angular/cli`. In the work, I'll try to fix the issue.

**Comment by hstarorg** [comment]
Please try with `ngx-ckeditor@beta`. I hope your feedback, thanks.

**Comment by joehansen** [comment]
Yeah, seems to work :-) Thx

**Comment by hstarorg** [comment]
@joehansen Thanks. In this week, I'll set this version to latest.

**Comment by hstarorg** [comment]
Published with tag `latest`.
