### ISSUE TITLE
Using ckeditor with out cdn

### ISSUE THREAD

**Issue by gaganhn** [HstarComponents/ngx-ckeditor#34]
I have a requirement to implement ckeditor without using cdn.

Can anyone help me do this ??

**Comment by gaganhn** [comment]
I have already tried using CKEditor full package from https://ckeditor.com/ckeditor-4/download/
But it throws error as showed below
<img width="1670" alt="screen shot 2018-10-24 at 11 29 37 am" src="https://user-images.githubusercontent.com/26406858/47409372-2fa61780-d780-11e8-9c28-60a713914313.png">

Couldn't find any issues relevant to me.

My implementation

<img width="939" alt="screen shot 2018-10-24 at 11 34 53 am" src="https://user-images.githubusercontent.com/26406858/47409662-0c2f9c80-d781-11e8-9d6c-23d19c60ab22.png">

<img width="828" alt="screen shot 2018-10-24 at 11 33 35 am" src="https://user-images.githubusercontent.com/26406858/47409555-bd820280-d780-11e8-929e-928dd7516f8c.png">

**Comment by hstarorg** [comment]
Please ensure has global variable `CKEDITOR` in `window`.

**Comment by gaganhn** [comment]
Yes I do have the global variable, 
I found a workaround, injecting ckeditor.js script file in index.html works.

**Comment by hstarorg** [comment]
@gaganhn Nice. Dynamic inject is very useful.
