### ISSUE TITLE
how to update config , it should display bold, italic and underline menu from the toolbar

### ISSUE THREAD

**Issue by divya130** [HstarComponents/ngx-ckeditor#35]
![capture](https://user-images.githubusercontent.com/9946399/47967039-405b6500-e07f-11e8-84d1-ba7c21964c36.PNG)

i have to hide all other options

**Comment by hstarorg** [comment]
Please see this demo: https://hstarcomponents.github.io/ngx-ckeditor/#/dynamic-config

Set the config like `{"forceEnterMode":true,"height":250, "removeButtons": "Bold,Italic,Underline"}`

The final config can be find in https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removeButtons

**Comment by hstarorg** [comment]
Also, the `toolbar` config will help you. https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbar

**Comment by divya130** [comment]
thank you.
