### ISSUE TITLE
How to insert text at cursor position in angular 6 ?

### ISSUE THREAD

**Issue by harshadvala** [HstarComponents/ngx-ckeditor#36]

**Comment by hstarorg** [comment]
Maybe you should operate the ckeditor instance by `ElementRef`.

**Comment by apurv195** [comment]
1. add (blur) event in your HTML like, (blur)="ckEditorOnBlur($event)"
2. add function in your component
       
        `public ckEditorOnBlur(event) {
        var selection = event.editor.getSelection();
        var ranges = selection.getRanges();
        var range = ranges[0];

        // Create a new range from the editor object
        var newRange = event.editor.createRange();

        // assign the newRange to move to the end of the current selection
        // using the range.endContainer element.
        var moveToEnd = true;
        newRange.moveToElementEditablePosition(range.endContainer, moveToEnd);

        // change selection
        var newRanges = [newRange];
        selection.selectRanges(newRanges);
        // now I can insert html without erasing the previously selected text.
        // event.editor.insertHtml("<span>Hello World!</span>");

        this.ckEditorBlurEle = event;
        this.ckEditorBlurEle.editor.insertHtml("Hello World...!");
        }`
3. whenever your blur event call that time you will get text 'Hello World...!' at your last cursor position.
