### ISSUE TITLE
Word Count issue 

### ISSUE THREAD

**Issue by divya130** [HstarComponents/ngx-ckeditor#37]
I am not able to get the word count and character count in the editor section .

 editorConfig = {
    extraPlugins: 'wordcount',
    wordcount: {
      showWordCount: true,
      showCharCount: true
       maxWordCount: 4,
       maxCharCount: 10
    }
  };
i have used as above but im getting error ,  Resource name "wordcount" was not found at "https://cdn.ckeditor.com/4.9.2/full-all/plugins/wordcount/plugin.js?t=I3I7".

**Comment by hstarorg** [comment]
Please see demo [https://hstarcomponents.github.io/ngx-ckeditor/#/form](https://hstarcomponents.github.io/ngx-ckeditor/#/form) and see source code  https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/pages/reactive-form-demo/reactive-form-demo.component.ts

**Comment by hstarorg** [comment]
![image](https://user-images.githubusercontent.com/4043284/49331096-03798400-f5d3-11e8-9a72-310761f32e5c.png)
This is the deployment folder

**Comment by divya130** [comment]
{"forceEnterMode":true,
"height":250,
 "extraPlugins": "wordcount",
    "wordcount": {
      "showWordCount": true,
      "showCharCount": true,
       "maxWordCount": 4,
      "maxCharCount": 10
    }
}

https://hstarcomponents.github.io/ngx-ckeditor/#/dynamic-config
 hi sorry for the late reply , i have tested the above link  where word count is working but character count is  not working and if you update config by using above object you will get to know

**Comment by hstarorg** [comment]
In my test, if you update the config once, it will right working. But update config more times when characters is full, it is not working.

**Comment by hstarorg** [comment]
This maybe is the wordcount plugin bug, not `ngx-cheditor` issue. Now close the issue. If you have any questions, you can create a new issue, thanks.
