### ISSUE TITLE
Editor not working in Material Tab (mat-tab)

### ISSUE THREAD

**Issue by harshadvala** [HstarComponents/ngx-ckeditor#38]
Angular 6 Material Tab

![capture](https://user-images.githubusercontent.com/5895908/49459847-00220a80-f816-11e8-9b38-18ba6beeb855.JPG)

Console Error 

![capture1](https://user-images.githubusercontent.com/5895908/49459892-1cbe4280-f816-11e8-8a0e-2025eb5fbb94.JPG)

**Comment by hstarorg** [comment]
It seem ckeditor throw errors. Would you give me demo link? thanks.

**Comment by hstarorg** [comment]
Please try with `ngx-ckeditor@beta`, thanks. Demo in [https://hstarcomponents.github.io/ngx-ckeditor/#/material-tab](https://hstarcomponents.github.io/ngx-ckeditor/#/material-tab)

**Comment by hstarorg** [comment]
Published with tag `latest`.
