### ISSUE TITLE
error TS2304: Cannot find name 'CKEDITOR'

### ISSUE THREAD

**Issue by eliteluxury** [HstarComponents/ngx-ckeditor#4]
I'm using CKEDITOR as in the Readme.
As soon as run `ng build`, I got following error.

ERROR in src/app/example/modules/example-tests/components/writing/writing.component.ts(40,23): error TS2304: Cannot find name 'CKEDITOR'.

**Comment by hstarorg** [comment]
Thanks, I'll add the d.ts file to fix it.

**Comment by eliteluxury** [comment]
thanks

**Comment by hstarorg** [comment]
It's not a function bug, and you can ignore it for running.

This error is because the typescript can't find the `CKEDITOR` type define.

You can add `index.d.ts` and set contnet 
```
declare const CKEDITOR: any;
```

**Comment by eliteluxury** [comment]
Really good. 
It is going without any errors.
Thanks. 
Good experience for me.
Beka.

**Comment by hstarorg** [comment]
Maybe you can provide a pull request. Thank you!
