### ISSUE TITLE
how to use inline mode

### ISSUE THREAD

**Issue by amirbashiri** [HstarComponents/ngx-ckeditor#40]
hi
thanks for your time!
i want to use inline mode but i have error.error title is:
`ERROR TypeError: "b.container is undefined"`

i use it like below
```
<ck-editor name = "comments" [config]="editorConfig"  [inline]="true"  [(ngModel)] = "comments"></ck-editor>
```
what is my mistake?

**Comment by hstarorg** [comment]
What's the `editorConfig` object?

I add a demo for you. https://hstarcomponents.github.io/ngx-ckeditor/#/inline

**Comment by amirbashiri** [comment]
my editorConfig is : 
```
editorConfig = {
		removePlugins        : 'elementspath',
		allowedContent       : true,
		resize_enabled       : false,
		extraAllowedContent  : 'div(*)',
		contentsLangDirection: 'rtl',
		defaultLanguage      : 'fa',
		language             : 'fa',
		extraPlugins         : 'divarea',
		toolbar              : [
			['Source'],
			['Cut', 'Copy', '-', 'Undo', 'Redo'],
			['Bold', 'Italic', 'Underline', 'Strike'],
			['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
			['Link', 'Unlink'],
			['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar'],
			['Font', 'FontSize'],
			['TextColor', 'BGColor']

		],
	}
```
.
your demo is not working :|
it has error:
` ReferenceError: CKEDITOR is not defined`

![screenshot from 2019-01-09 16-08-57](https://user-images.githubusercontent.com/35067675/50899994-fa2cd400-1428-11e9-84e1-ccf512106f1e.png)

**Comment by hstarorg** [comment]
I think you should check your network by Chrome F12->Network.
![image](https://user-images.githubusercontent.com/4043284/50983333-3dc33300-153a-11e9-8544-086ec9460518.png)
The demo preview.

**Comment by hstarorg** [comment]
Also, I used your config in dynamic config, it working:
![image](https://user-images.githubusercontent.com/4043284/50983547-a0b4ca00-153a-11e9-9cbb-d365526a8fe5.png)

**Comment by hstarorg** [comment]
I changed the ckeditor cdn address from `https://cdn.bootcss.com/ckeditor/4.9.1/ckeditor.js` to `https://cdn.jsdelivr.net/npm/ckeditor@4.9.1/ckeditor.js`. I hope you can visit it.

**Comment by amirbashiri** [comment]
thanks for answer!
your demo is working now
please add demo typescript source in demo page
thank you

**Comment by amirbashiri** [comment]
hi!
thanks for answer!
i think i find my problem!
i cant load ckeditor from cdn in my project ,so i download ckeditor package from this link:
`https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.11.1/ckeditor_4.11.1_full_easyimage.zip`
and link the script to  my project like this:
`<script src = "assets/plugins/ckeditor/ckeditor.js"></script>`
please tell if its wrong way!
also i link the script from cdn like your demo but i still hav error `b.container is undefined`
can you run project from internal js file in stackblitz please?!!??!?

**Comment by hstarorg** [comment]
Make sure the ckedtior.js is load successfully. The stackblitz demo: https://stackblitz.com/edit/angular-yjacl3

**Comment by amirbashiri** [comment]
my problem was fixed!
i use ngx-ckeditor from original component in github version
i think the node_modules version of ngx-editor was my problem
i add your original ngx-ckeditor (not compiled version) and my problem was fixed
anyway,thanks for your time and your component .
good luck by firend

**Comment by hstarorg** [comment]
This is the another usage. Also, you can customize it by a little change.
