### ISSUE TITLE
how to find ckeditor cdn link with https?

### ISSUE THREAD

**Issue by apurv195** [HstarComponents/ngx-ckeditor#42]
1. i am using "ngx-ckeditor": "^0.4.0"
2. including cdn link in index.html
`<script src="//cdn.ckeditor.com/4.7.1/full/ckeditor.js"></script>`
3. it was working fine in my local system, but not working on Live server, it's because of 'http' , i want cdn link with 'https'
4. i got Error like 'ckeditor 4.X is missing'
5. how can i find ckeditor cdn with 'https'
6. Download cdn link also not working, getting error like, **something was undefined**

**Comment by hstarorg** [comment]
You can use `https://cdn.ckeditor.com/4.7.1/full/ckeditor.js`. Maybe you should check your network. In my test, I can get the `https://cdn.ckeditor.com/4.7.1/full/ckeditor.js` content.
