### ISSUE TITLE
How to add custom button in ngx-ckeditor?

### ISSUE THREAD

**Issue by apurv195** [HstarComponents/ngx-ckeditor#43]
1. i am using "ngx-ckeditor": "^0.4.0",
2. i want to add my custom icon & access it's click event in angular 5.
3. i am trying to hide Image dialog while click on Image icon, but it's not working
`
    this.ckEditorConfig = {
            on: {
                afterCommandExec: function handleAfterCommandExec(event) {
                    if (event.data.name == 'image') {
                        that.fileUploadImage.nativeElement.click();
                        var startFind = setInterval(() => {
                            if($(".cke_dialog_ui_button_cancel span").length > 0){
                                clearInterval(startFind);
                                $(".cke_dialog_ui_button_cancel span").click();
                            }
                        }, 200);
                    }
                },
            },
    };
`

> with this code when i click on Image icon first Image dialog open and then hide, but i don't want to open it, without remove it's plugin

**Comment by hstarorg** [comment]
Please see:
1. https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/pages/basic-demo/basic-demo.component.ts
2. https://hstarcomponents.github.io/ngx-ckeditor/#/

**Comment by apurv195** [comment]
1. using your code i am getting error like **Module not found: Error: Can't resolve 'ngx-ckeditor/lib/ck-editor.component'**
2. i am importing component like below,
`import { CKEditorComponent } from 'ngx-ckeditor/lib/ck-editor.component';`

**Comment by hstarorg** [comment]
Only import it from 'ngx-ckeditor'
