### ISSUE TITLE
how to add equation editor in ngx-ckeditor

### ISSUE THREAD

**Issue by asif212** [HstarComponents/ngx-ckeditor#45]

**Comment by hstarorg** [comment]
This is only the ck-editor angular wrapper, you can use ck editor function to add equation editor.

**Comment by asif212** [comment]
Thank you for your help. I am new in angular will you please help me to Implement ckeditor in angular 4 with wiris plugin.
I am able to integrate ckeditor without any plugin with cdn of ckeditor.

I have downloaded the external js of ckeditor with all plugins. But can't able to use in angular 4 project.

**Comment by hstarorg** [comment]
There is a plugin demo: https://hstarcomponents.github.io/ngx-ckeditor/#/form ,
the page source is: https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/pages/reactive-form-demo/reactive-form-demo.component.ts
