### ISSUE TITLE
unable to find moono-lisa css file

### ISSUE THREAD

**Issue by radici** [HstarComponents/ngx-ckeditor#47]
Refused to apply style from 'http://localhost:4200/.../skins/moono-lisa/editor.css?t=H5SC' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by hstarorg** [comment]
Check the skins is exists.

**Comment by phil123456** [comment]
same here, it cannot load css

**Comment by hstarorg** [comment]
Okay, I'll confirm this question.

**Comment by phil123456** [comment]
any fix yet ? I mean , the component is basicaly unusable with recent angular versions

**Comment by hstarorg** [comment]
@radici How did you inject the ckeditor js file?
In my demo, I used `<script src="https://cdn.jsdelivr.net/npm/ckeditor@4.9.1/ckeditor.js"></script>`, it works fine.
![image](https://user-images.githubusercontent.com/4043284/60751602-986db100-9fea-11e9-9ea8-8d864ca3793d.png)

**Comment by phil123456** [comment]
yes, I just add the <script> tag
seems like the url gets sanitised or something
why did admin closed this ?

**Comment by hstarorg** [comment]
@phil123456 I can't reproduce the question, would you provide more info.  In my online demo(https://hstarcomponents.github.io/ngx-ckeditor/), it's work fine, you can check your environment.

**Comment by phil123456** [comment]
Hi,

can you give the url of the repo? so I can compare the code and package.json files

thanks

**Comment by hstarorg** [comment]
The repo is: https://github.com/HstarComponents/ngx-ckeditor/tree/master/examples
