### ISSUE TITLE
Angular 7 - cannot import js file, script tag gets removed

### ISSUE THREAD

**Issue by phil123456** [HstarComponents/ngx-ckeditor#48]
hello,

I try to add <script src="//cdn.ckeditor.com/4.7.1/full/ckeditor.js"></script> to my index.html but it gets removed

if I donwload the "ckeditor.js" and put it in my assets folder, loading it with angular.json "scripts" entry point, then the script loads but it cannot find languages and css files

can you update your documentation for angular 7 ?, aparently it does not work anymore

regards

```
{
  "name": "editor-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "core-js": "^2.5.4",
    "ngx-ckeditor": "^0.4.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.0",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}

```

**Comment by hstarorg** [comment]
The document are used angular 7.x. I think you should check your build progress.

**Comment by phil123456** [comment]
> The document are used angular 7.x. I think you should check your build progress.

I know all the words in this phrase , yet I dont understand what you're trying to communicate
I'll try updating my project if it's what you mean
;-)

**Comment by hstarorg** [comment]
Sorry, my English is a little poor.  
The repo demo url(https://hstarcomponents.github.io/ngx-ckeditor/) are build with angular 7.x and ckedtior 4.9.1, it works fine.

**Comment by hstarorg** [comment]
ngx-ckeditor@8.0.0 for angular.x released.

**Comment by phil123456** [comment]
just updated , it simply does not work

it cannot even find the files on the cdn...I am going for a mor decent editor

https://i.imgur.com/b7PGdBe.png

**Comment by hstarorg** [comment]
Why not see my demo : https://github.com/HstarComponents/ngx-ckeditor/tree/master/examples 
If you can't find ckeditor in cdn, you can download it on your project.

**Comment by phil123456** [comment]
ok I finaly found the issue
the script tag must be in index.html, not app.component.html
my bad

**Comment by hstarorg** [comment]
That's good.
