### ISSUE TITLE
Do we have insert media option in ngx-ckeditor ?

### ISSUE THREAD

**Issue by hmk18** [HstarComponents/ngx-ckeditor#49]

**Comment by hstarorg** [comment]
`ngx-ckeditor` is only a ckeditor wrapper. You can customize you function like https://github.com/HstarComponents/ngx-ckeditor/blob/master/examples/pages/basic-demo/basic-demo.component.ts#L36-L73`

**Comment by hstarorg** [comment]
No response for a long time, closed
