### ISSUE TITLE
How to specifies the text displayed in the editor when there is no content (editor is empty)

### ISSUE THREAD

**Issue by anoop-chauhan** [HstarComponents/ngx-ckeditor#52]
Hi, how can we specify the text displayed in the editor when there is no content (editor is empty). wants to work similarly as to the native DOM placeholder attribute used by inputs.

**Reference Docs:**  [CK-EDITOR](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html#using-the-editor-configuration)

**Comment by hstarorg** [comment]
This component was depend on ckeditor 4.x. I can't sure the placeholder can be supported.

**Comment by hstarorg** [comment]
@anoop-chauhan See: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-editorplaceholder

**Comment by hstarorg** [comment]
No more info, closed
