### ISSUE TITLE
cke editor converting html to cke_protected.

### ISSUE THREAD

**Issue by idineshgarg** [HstarComponents/ngx-ckeditor#59]
[1618575542921index (1).txt](https://github.com/HstarComponents/ngx-ckeditor/files/6399822/1618575542921index.1.txt)

Tried to paste this file but gets converted to {cke_protected} at multiple points. Need assistance why such thing is happening.
using "version":4 of ngx-ckeditor

**Comment by hstarorg** [comment]
Try to upgrade your ckeditor version to 4.16.2.

**Comment by hstarorg** [comment]
Also, would you paste your ckeditor config?

**Comment by hstarorg** [comment]
No feedback too long, closed.
