### ISSUE TITLE
ERROR in : Unexpected value 'CKEditorModule in 

### ISSUE THREAD

**Issue by asthay43** [HstarComponents/ngx-ckeditor#6]
Hi,
At the time of simple ng build its working fine.
But when I'm trying to use ng build --prod --aot error below.

ERROR in : Unexpected value 'CKEditorModule in /home/node_modules/ngx-ckeditor/lib/ck-editor.module.d.ts' imported by the module 'ClientsModule in /home/web-app/src/app/controller/contractor/clients/clients.module.ts'. Please add a @NgModule annotation.

**Comment by hstarorg** [comment]
Thanks. I'll try this scenes.

**Comment by anuraggu** [comment]
Hi
i am facing same issue.

ERROR in : Unexpected value 'CKEditorModule in /home/matrix/Desktop/project/citrus/front_end/node_modules/ngx-ckeditor/lib/ck-editor.module.d.ts' imported by the module 'AppModule in /home/project/xxx/front_end/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by GianGoulart94** [comment]
Hi

I have the same issue

ERROR in : Unexpected value 'CKEditorModule in C:/e-Aceites_Admin/my-app/node_modules/ngx-ckeditor/lib/ck-editor.module.d.ts' imported by the module 'AppModule in C:/e-Aceites_Admin/my-app/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by hstarorg** [comment]
I'll fix it at this week.

**Comment by hstarorg** [comment]
Fix it at 0.3.0, but the metadata version is 4 that only for angular 5.x

**Comment by hstarorg** [comment]
issue fixed.
