### ISSUE TITLE
'ck-editor' is not a known element in angular 5

### ISSUE THREAD

**Issue by himanajju** [HstarComponents/ngx-ckeditor#7]
'ck-editor' is not a known element:
1. If 'ck-editor' is an Angular component, then verify that it is part of this module.
2. If 'ck-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by martinobordin** [comment]
How did you fix it?

**Comment by hstarorg** [comment]
What's happen?

**Comment by martinobordin** [comment]
I have the same issue with angular 4 when building with ng build --prod

Il mer 4 lug 2018, 19:20 Jay.M.Hu <notifications@github.com> ha scritto:

**Comment by hstarorg** [comment]
@martinobordin  Maybe you should install by `ngx-ckeditor@0.2.x`, The `0.2.x` is for angular 4.x.
See [https://github.com/HstarComponents/ngx-ckeditor](https://github.com/HstarComponents/ngx-ckeditor) FAQ Section.

**Comment by DhrubajitPC** [comment]
I am facing the same issue, any updates on this? using ngx-ckeditor@0.2.x with angular 4

**Comment by hstarorg** [comment]
Try install by `ngx-ckeditor@0.2.x `

**Comment by DhrubajitPC** [comment]
hi @hstarorg ... I was using `ngx-ckeditor@0.2.x`. It appears that somehow it doesn't work on the project I am working on now but it works on any new project I create. I think there are issues with how my current project is structured. Thanks for the quick response.

**Comment by hstarorg** [comment]
Maybe you can provide a simple demo for me, thanks.

**Comment by hstarorg** [comment]
Would you try the next version in angular4?

**Comment by hstarorg** [comment]
Make sure you are imported the `CKEditorModule` in the `app.module.ts`

**Comment by Gotemperor** [comment]
which version are we talking exactly? because I also tried the latest version (yeastarday) without any success

**Comment by hstarorg** [comment]
Would you give me a simple demo app? In my test, it works.

**Comment by Sevensnake** [comment]
does not work with angular 9

**Comment by hstarorg** [comment]
I'll adapt the angular 9 in next  9.x version

**Comment by Max-Power-7** [comment]
I also was have same problem.
¿Solution? reboot VSCode...

Have all equal to documentation
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start

**Comment by hstarorg** [comment]
> I also was have same problem. ¿Solution? reboot VSCode...
> 
> Have all equal to documentation https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start

Readme updated.
