### ISSUE TITLE
Unable to install ckeditor in angular 4.X

### ISSUE THREAD

**Issue by vinodhram3** [HstarComponents/ngx-ckeditor#8]
Command Use - npm i -S ngx-ckeditor@2
Error:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ngx-ckeditor@2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

**Comment by hstarorg** [comment]
I‘m sorry, please use `npm i ngx-ckeditor@0.2.0` install the for angular 4.x version.
